#define SPMD
#define  SYNCH
#undef  FRC_ANN
#define CDFIN
#undef  FRC_DAILY
#undef  FRC_CORE
#define SOLAR
#define  ACOS
#undef  BIHAR
#undef  SMAG_FZ
#undef  SMAG_OUT
#define NETCDF
#undef BOUNDARY
#define NODIAG
#undef  ICE
#undef SHOW_TIME
#define DEBUG
#define COUP
#define  ISO
#define D_PRECISION
#define  CANUTO
#undef SOLARCHLORO
#undef LDD97
#undef TSPAS
#undef  SMAG
#define BACKMX
#define NEWSSBC1
#define seaice1
#define omipout
#undef cpldt
#undef BACKD
#undef biochem
#define  USE_OCN_CARBON
#undef   carbonC14
#undef   carbonC
#define  carbonBio
#undef  Felimit
#define mom_xu_pt
#undef   scav_moore08
#undef   carbonAbio
#define  preindustrial
#undef  murnane1999
#define  anderson1995
#undef   progca
#undef   buchang
#undef   carbonDebug
#undef   printcall
#undef   nc14wind
#define  o2limit
#undef CO2
