
subroutine cal_cosfai(GMT,JULIAN,XLONG,XLAT,CSZA) 

implicit none
real,parameter :: pi=3.1415926
real,parameter :: DPD=360.0/365.0
real,parameter :: DEGRAD=pi/180.0

integer :: JULIAN

real :: DECLIN,SOLCON

real :: SXLONG,ARG

real :: DECDEG,OBECL,SINOB

real :: DJUL,RJUL

real :: ECCFAC

real :: GMT 

real :: XLONG,XLAT,XXLAT
real :: HRANG,TLOCTM

real :: CSZA

   DECLIN=0.
   SOLCON=0.

!-----OBECL : OBLIQUITY = 23.5 DEGREE.

   OBECL=23.5*DEGRAD
   SINOB=SIN(OBECL)

!-----CALCULATE LONGITUDE OF THE SUN FROM VERNAL EQUINOX:

   JULIAN=80


   IF(JULIAN.GE.80.)SXLONG=DPD*(JULIAN-80.)
   IF(JULIAN.LT.80.)SXLONG=DPD*(JULIAN+285.)
   SXLONG=SXLONG*DEGRAD
   ARG=SINOB*SIN(SXLONG)
   DECLIN=ASIN(ARG)
   DECDEG=DECLIN/DEGRAD
!----SOLAR CONSTANT ECCENTRICITY FACTOR (PALTRIDGE AND PLATT 1976)
   DJUL=JULIAN*360./365.
   RJUL=DJUL*DEGRAD
   ECCFAC=1.000110+0.034221*COS(RJUL)+0.001280*SIN(RJUL)+0.000719*  &
          COS(2*RJUL)+0.000077*SIN(2*RJUL)
   SOLCON=1370.*ECCFAC
  
   !print*,'SOLCON=',SOLCON


   !XLONG=120
   !XLAT=40

   !read(*,*) GMT

   TLOCTM=GMT+XLONG/15.
   HRANG=15.*(TLOCTM-12.)*DEGRAD
   XXLAT=XLAT*DEGRAD
   CSZA=SIN(XXLAT)*SIN(DECLIN)+COS(XXLAT)*COS(DECLIN)*COS(HRANG)

   print*,'CSZA=',CSZA

end

