
integer,parameter :: &

  idx_h2so4gas=1 &
 ,idx_hno3=2 &
 ,idx_hcl=3 &
 ,idx_nh3=4 &
 ,idx_no=5 &
 ,idx_no2=6 &

 ,idx_no3=7 &
 ,idx_n2o5=8 &
 ,idx_hono=9 &
 ,idx_hno4=10 &
 ,idx_o3=11 &
 ,idx_o1d=12 &

 ,idx_o3p=13 &
 ,idx_oh=14 &
 ,idx_ho2=15 &
 ,idx_h2o2=16 &
 ,idx_co=17 &
 ,idx_so2=18 &

 ,idx_ch4=19 &
 ,idx_c2h6=20 &
 ,idx_ch3o2=21 &
 ,idx_ethp=22 &
 ,idx_hcho=23 &
 ,idx_ch3oh=24 &

 ,idx_anol=25 &
 ,idx_ch3ooh=26 &
 ,idx_theooh=27 &
 ,idx_ald2=28 &
 ,idx_hcooh=29 &
 ,idx_rcooh=30 &

 ,idx_c2o3=31 &
 ,idx_pan=32 &
 ,idx_par=33 &
 ,idx_aone=34 &
 ,idx_mgly=35 &
 ,idx_eth=36 &

 ,idx_olet=37 &
 ,idx_olei=38 &
 ,idx_tol=39  &
 ,idx_xyl=40 &
 ,idx_cres=41 &
 ,idx_to2=42 &

 ,idx_cro=43 &
 ,idx_open=44 &
 ,idx_onit=45 &
 ,idx_rooh=46 &
 ,idx_ro2=47 &
 ,idx_ano2=48 &

 ,idx_nap=49 &
 ,idx_xo2=50 &
 ,idx_xpar=51 &
 ,idx_isop=52 &
 ,idx_isoprd=53 &
 ,idx_isopp=54 &

 ,idx_isopn=55 &
 ,idx_isopo2=56 &
 ,idx_dms=57 &
 ,idx_msa=58 &
 ,idx_dmso=59 &
 ,idx_dmso2=60 &
 
 ,idx_ch3so2h=61 &
 ,idx_ch3sch2oo=62 &
 ,idx_ch3so2=63 &
 ,idx_ch3so3=64 &
 ,idx_ch3so2oo=65 &
 ,idx_ch3so2ch2oo=66 &

 ,idx_sulfhox=67 &
 ,idx_terp=68 &
 ,idx_sv1=69 &
 ,idx_sv2=70 &
 ,idx_sv3=71 &
 ,idx_sv4=72 &

 ,idx_sv5=73 &
 ,idx_sv6=74 &
 ,idx_pm25=75 &
 ,idx_pm10=76 &
 ,idx_bc=77 &
 ,idx_oc=78 &

 ,idx_haq=79 &

 ,idx_naaq=80 &
 ,idx_nh4aq=81 &
 ,idx_claq=82 &
 ,idx_so4aq=83 &
 ,idx_hso4aq=84 &
 ,idx_no3aq=85 &

 ,idx_nacls=86 &
 ,idx_na2so4=87 &
 ,idx_nano3=88 &
 ,idx_nh42so4=89 &
 ,idx_nh4no3=90 &
 ,idx_nh4cl=91 &

 ,idx_h2so4s=92 &
 ,idx_nh4hso4=93 &
 ,idx_nahso4=94 &
 ,idx_nh44hso42=95 &
 ,idx_soa1=96 &

 ,idx_soa2=97 &
 ,idx_soa3=98 &
 ,idx_soa4=99 &
 ,idx_soa5=100 &
 ,idx_soa6=101 &
 ,idx_ah2o=102



end
