      module mo_adjrxt
      private
      public :: adjrxt
      contains
      subroutine adjrxt( rate, inv, m, ncol )
      use ppgrid, only : pver
      use shr_kind_mod, only : r8 => shr_kind_r8
      use chem_mods, only : nfs, rxntot
      implicit none
!--------------------------------------------------------------------
! ... dummy arguments
!--------------------------------------------------------------------
      integer, intent(in) :: ncol
      real(r8), intent(in) :: inv(ncol,pver,nfs)
      real(r8), intent(in) :: m(ncol,pver)
      real(r8), intent(inout) :: rate(ncol,pver,rxntot)
!--------------------------------------------------------------------
! ... local variables
!--------------------------------------------------------------------
      integer :: k
      real(r8) :: im(ncol)
      do k = 1,pver
         rate(:,k, 21) = rate(:,k, 21) * inv(:,k, 1)
         rate(:,k, 22) = rate(:,k, 22) * inv(:,k, 2)
         rate(:,k, 23) = rate(:,k, 23) * inv(:,k, 3)
         rate(:,k, 24) = rate(:,k, 24) * inv(:,k, 4)
         rate(:,k, 42) = rate(:,k, 42) * inv(:,k, 1)
         rate(:,k, 48) = rate(:,k, 48) * inv(:,k, 1)
         rate(:,k, 52) = rate(:,k, 52) * inv(:,k, 1)
         rate(:,k, 54) = rate(:,k, 54) * inv(:,k, 1)
         rate(:,k, 55) = rate(:,k, 55) * inv(:,k, 1)
         rate(:,k, 56) = rate(:,k, 56) * inv(:,k, 1)
         rate(:,k, 61) = rate(:,k, 61) * inv(:,k, 1)
         rate(:,k, 63) = rate(:,k, 63) * inv(:,k, 1)
         rate(:,k, 72) = rate(:,k, 72) * inv(:,k, 1)
         rate(:,k, 76) = rate(:,k, 76) * inv(:,k, 1)
         rate(:,k, 77) = rate(:,k, 77) * inv(:,k, 1)
         rate(:,k, 80) = rate(:,k, 80) * inv(:,k, 1)
         rate(:,k, 19) = rate(:,k, 19) * inv(:,k, 3) * inv(:,k, 1)
         rate(:,k, 33) = rate(:,k, 33) * inv(:,k, 3) * inv(:,k, 1)
         rate(:,k, 20) = rate(:,k, 20) * m(:,k)
         rate(:,k, 21) = rate(:,k, 21) * m(:,k)
         rate(:,k, 25) = rate(:,k, 25) * m(:,k)
         rate(:,k, 26) = rate(:,k, 26) * m(:,k)
         rate(:,k, 27) = rate(:,k, 27) * m(:,k)
         rate(:,k, 28) = rate(:,k, 28) * m(:,k)
         rate(:,k, 29) = rate(:,k, 29) * m(:,k)
         rate(:,k, 30) = rate(:,k, 30) * m(:,k)
         rate(:,k, 31) = rate(:,k, 31) * m(:,k)
         rate(:,k, 32) = rate(:,k, 32) * m(:,k)
         rate(:,k, 34) = rate(:,k, 34) * m(:,k)
         rate(:,k, 35) = rate(:,k, 35) * m(:,k)
         rate(:,k, 36) = rate(:,k, 36) * m(:,k)
         rate(:,k, 37) = rate(:,k, 37) * m(:,k)
         rate(:,k, 38) = rate(:,k, 38) * m(:,k)
         rate(:,k, 39) = rate(:,k, 39) * m(:,k)
         rate(:,k, 40) = rate(:,k, 40) * m(:,k)
         rate(:,k, 41) = rate(:,k, 41) * m(:,k)
         rate(:,k, 42) = rate(:,k, 42) * m(:,k)
         rate(:,k, 43) = rate(:,k, 43) * m(:,k)
         rate(:,k, 44) = rate(:,k, 44) * m(:,k)
         rate(:,k, 45) = rate(:,k, 45) * m(:,k)
         rate(:,k, 46) = rate(:,k, 46) * m(:,k)
         rate(:,k, 47) = rate(:,k, 47) * m(:,k)
         rate(:,k, 48) = rate(:,k, 48) * m(:,k)
         rate(:,k, 49) = rate(:,k, 49) * m(:,k)
         rate(:,k, 50) = rate(:,k, 50) * m(:,k)
         rate(:,k, 51) = rate(:,k, 51) * m(:,k)
         rate(:,k, 52) = rate(:,k, 52) * m(:,k)
         rate(:,k, 53) = rate(:,k, 53) * m(:,k)
         rate(:,k, 54) = rate(:,k, 54) * m(:,k)
         rate(:,k, 56) = rate(:,k, 56) * m(:,k)
         rate(:,k, 57) = rate(:,k, 57) * m(:,k)
         rate(:,k, 58) = rate(:,k, 58) * m(:,k)
         rate(:,k, 59) = rate(:,k, 59) * m(:,k)
         rate(:,k, 60) = rate(:,k, 60) * m(:,k)
         rate(:,k, 61) = rate(:,k, 61) * m(:,k)
         rate(:,k, 62) = rate(:,k, 62) * m(:,k)
         rate(:,k, 64) = rate(:,k, 64) * m(:,k)
         rate(:,k, 65) = rate(:,k, 65) * m(:,k)
         rate(:,k, 66) = rate(:,k, 66) * m(:,k)
         rate(:,k, 67) = rate(:,k, 67) * m(:,k)
         rate(:,k, 68) = rate(:,k, 68) * m(:,k)
         rate(:,k, 69) = rate(:,k, 69) * m(:,k)
         rate(:,k, 70) = rate(:,k, 70) * m(:,k)
         rate(:,k, 71) = rate(:,k, 71) * m(:,k)
         rate(:,k, 72) = rate(:,k, 72) * m(:,k)
         rate(:,k, 73) = rate(:,k, 73) * m(:,k)
         rate(:,k, 74) = rate(:,k, 74) * m(:,k)
         rate(:,k, 75) = rate(:,k, 75) * m(:,k)
         rate(:,k, 76) = rate(:,k, 76) * m(:,k)
         rate(:,k, 78) = rate(:,k, 78) * m(:,k)
         rate(:,k, 79) = rate(:,k, 79) * m(:,k)
         rate(:,k, 80) = rate(:,k, 80) * m(:,k)
         rate(:,k, 81) = rate(:,k, 81) * m(:,k)
         rate(:,k, 82) = rate(:,k, 82) * m(:,k)
         rate(:,k, 83) = rate(:,k, 83) * m(:,k)
         rate(:,k, 84) = rate(:,k, 84) * m(:,k)
         rate(:,k, 85) = rate(:,k, 85) * m(:,k)
         rate(:,k, 86) = rate(:,k, 86) * m(:,k)
         rate(:,k, 87) = rate(:,k, 87) * m(:,k)
         rate(:,k, 88) = rate(:,k, 88) * m(:,k)
         rate(:,k, 89) = rate(:,k, 89) * m(:,k)
         rate(:,k, 90) = rate(:,k, 90) * m(:,k)
         rate(:,k, 91) = rate(:,k, 91) * m(:,k)
         rate(:,k, 95) = rate(:,k, 95) * m(:,k)
         rate(:,k, 96) = rate(:,k, 96) * m(:,k)
         rate(:,k, 97) = rate(:,k, 97) * m(:,k)
         rate(:,k, 98) = rate(:,k, 98) * m(:,k)
      end do
      end subroutine adjrxt
      end module mo_adjrxt
