#define  COUP_CSM
#undef  CPL6
#define  CPL7
#undef  RDGRID
#undef  RDGRID2
#undef  SURFREF
#undef  SOILINI
#undef  EcoDynamics
#define PFT
#define DGVM
#undef  BNUDGVM
#define  IAPDGVM
#undef  VEGDATA
#undef  DyN
#undef  SINGLE
#undef  LAND_SEA
#undef  SINGLE_POINT
#undef  GLACIER
#define AUTOMASK
#undef  PRINCETON
#undef  GSWP2
#define CRUNCEP
#undef  FLUXNET
#undef  RTM
#define SPMD
#define LINUX
#undef  MYBUG
#undef  SITE_VALDAI
#undef  SITE_SODAN
#undef  SOIL10
#define SOIL15
