      SUBROUTINE CALCLDOPD ( CLWP, CLDOPD, RAINCV, RAINNCV)
! ***    TO CALCULATE THE CLOUD OPTICAL DEPTH  ****
! **  USING LIU AND MAO(2008) IN ACTA SCIENTRIARUM NATURALIUM UNVERSITARIES PEKINENSIS, 44, NO1

      
      REAL  :: CLWP, CLDOPD, RAINCV, RAINNCV
      

!***  CLWP IS COLUMN CLOUD WATER IN G/M2 ASSUMING RATUS IS 11.85UM 
!***  CLDOPD IS CLOUD OPTICAL DEPTH      
!***  RAINCV IS CONVECTIVE RAINFALL       
!***  RAINNCV IS NON-CONVECTIVE RAINFALL      
!***  WE ASSUME RADIUS OF CLOUD DROPETS IS 11.85 UM FROM LIU AND MAO, FOR CONVECTIVE IS
!      35UM, NON-CONVECTIVE IS 22.5UM
      IF( RAINCV .GE. 0.05) THEN
        R = 35.
      ELSE IF( RAINNCV .GE. 0.01) THEN
        R = 22.5
      ELSE
        R = 11.85
      ENDIF      
      
      CLDOPD = CLWP / (2.* R /3.)
     
      CLDOPD = MAX(CLDOPD, 1.0)       

      ENDSUBROUTINE
